"""Check whether every forecast row generated by the Week 3 CLI is uploaded to BigQuery."""
from __future__ import annotations

import json
import os
import sys

lines: list[str] = []


def log(message: object = "") -> None:
    lines.append(str(message))


# 1. Python packages needed for the BigQuery upload
log("== Python packages ==")
from importlib.metadata import distributions  # noqa: E402

installed = {dist.metadata["Name"].lower(): dist.version for dist in distributions()}
for package in (
    "pandas-gbq",
    "google-cloud-bigquery",
    "google-auth",
    "db-dtypes",
    "pandas",
    "lightgbm",
    "prophet",
):
    log(f"{package}: {installed.get(package, 'NOT INSTALLED')}")

# 2. Application Default Credentials used by pandas_gbq
log()
log("== Application Default Credentials (ADC) ==")
candidates = [
    os.environ.get("GOOGLE_APPLICATION_CREDENTIALS", ""),
    os.path.join(os.environ.get("APPDATA", ""), "gcloud", "application_default_credentials.json"),
    os.path.join(os.environ.get("USERPROFILE", ""), ".config", "gcloud", "application_default_credentials.json"),
]
adc_found = False
for path in candidates:
    if path:
        log(f"{path}: {'EXISTS' if os.path.exists(path) else 'missing'}")
        adc_found = adc_found or os.path.exists(path)
if not adc_found:
    log("ADC: NOT FOUND -> pandas_gbq.to_gbq would fail to authenticate")

# 3. Local forecast artifacts that may never have been uploaded
log()
log("== Local forecast artifacts (csv/parquet/pkl/joblib) ==")
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
found_any = False
for base, dirs, files in os.walk(root):
    dirs[:] = [d for d in dirs if d not in {".venv", ".git", "__pycache__", "node_modules"}]
    for name in files:
        if name.lower().endswith((".csv", ".parquet", ".pkl", ".joblib")):
            full = os.path.join(base, name)
            found_any = True
            log(f"{full} ({os.path.getsize(full)} bytes)")
if not found_any:
    log("None found - forecasts are only produced in-memory and written straight to BigQuery")

# 4. Live BigQuery check of raw inputs and forecast outputs
log()
log("== BigQuery datasets and tables ==")
project_id = "fresh-yen-508710-a0-509416"
datasets = {
    "m5_raw": {
        "Calendar",
        "sales_train_validation",
        "sales_train_evaluation",
        "sell_prices",
        "sample_submission",
    },
    "dbt_dev_sachin": {"forecasting_input", "forecasts", "forecast_metrics"},
}
try:
    import pandas_gbq

    available_tables: dict[str, set[str]] = {}
    for dataset, expected_tables in datasets.items():
        log()
        try:
            tables = pandas_gbq.read_gbq(
                f"SELECT table_name, table_type "
                f"FROM `{project_id}.{dataset}.INFORMATION_SCHEMA.TABLES` "
                "ORDER BY table_name",
                project_id=project_id,
                dialect="standard",
            )
            available_tables[dataset] = set(tables["table_name"].astype(str))
            log(f"{project_id}.{dataset}: {len(tables)} table(s)")
            log(tables.to_string(index=False) if not tables.empty else "No tables found")
            missing = sorted(expected_tables - available_tables[dataset])
            if missing:
                log(f"MISSING expected tables: {', '.join(missing)}")
        except Exception as error:  # noqa: BLE001
            available_tables[dataset] = set()
            log(f"{project_id}.{dataset}: unavailable: {type(error).__name__}: {error}")

    if "forecasts" in available_tables.get("dbt_dev_sachin", set()):
        log()
        log(f"-- {project_id}.dbt_dev_sachin.forecasts --")
        summary = pandas_gbq.read_gbq(
            f"""
            SELECT model_name, COUNT(*) AS row_count, MIN(date) AS min_date,
                   MAX(date) AS max_date, MAX(generated_at) AS last_generated_at,
                   COUNT(DISTINCT generated_at) AS distinct_runs
            FROM `{project_id}.dbt_dev_sachin.forecasts`
            GROUP BY model_name
            ORDER BY model_name
            """,
            project_id=project_id,
            dialect="standard",
        )
        log(summary.to_string(index=False))

        completeness = pandas_gbq.read_gbq(
            f"""
            SELECT generated_at, COUNT(*) AS uploaded_rows,
                   COUNT(DISTINCT CONCAT(COALESCE(item_id, '~'), '|', COALESCE(store_id, '~'),
                                         '|', COALESCE(state_id, '~'), '|', COALESCE(dept_id, '~'))) AS series,
                   MIN(date) AS min_date, MAX(date) AS max_date,
                   COUNT(DISTINCT date) AS distinct_dates
            FROM `{project_id}.dbt_dev_sachin.forecasts`
            GROUP BY generated_at
            ORDER BY generated_at
            """,
            project_id=project_id,
            dialect="standard",
        )
        log("Forecast row completeness per run:")
        log(completeness.to_string(index=False))

    if "forecast_metrics" in available_tables.get("dbt_dev_sachin", set()):
        log()
        log(f"-- {project_id}.dbt_dev_sachin.forecast_metrics --")
        metrics = pandas_gbq.read_gbq(
            f"""
            SELECT model_name, COUNT(*) AS row_count, MAX(evaluated_at) AS last_evaluated_at
            FROM `{project_id}.dbt_dev_sachin.forecast_metrics`
            GROUP BY model_name
            ORDER BY model_name
            """,
            project_id=project_id,
            dialect="standard",
        )
        log(metrics.to_string(index=False))
except Exception as error:  # noqa: BLE001
    log(f"BigQuery unavailable: {type(error).__name__}: {error}")

report_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "check_bigquery_report.txt")
with open(report_path, "w", encoding="utf-8") as handle:
    handle.write("\n".join(lines))
print(json.dumps({"report": report_path, "lines": len(lines)}))
